### PR TITLE
Front end file size validation

### PR DESCRIPTION
**Pull request by mattboldt**
disregard the previous commits... I had a `requestType` property before I realized there was a `dropletOptions` object.

### CODE REVIEW

**Comment by Wildhoney** [comment]
Excellent addition! :+1: Although is there any chance we could bundle the `filesizeLimit` [as part of the `options` configuration](https://github.com/macroplant/EmberDroplet/blob/file-size-validation/dist/ember-droplet.js#L160) to be consistent?

**Comment by mattboldt** [comment]
Given this logic, the mimeTypes should also be in there.

**Comment by Wildhoney** [comment]
I agree :+1:

**Comment by Wildhoney** [comment]
Thanks! :beers: All merged.

**Pull request merged**
