### PR TITLE
Don't attempt to upload zero files

### LINKED ISSUE #106: Uploading zero files
In version 2.1.3, Droplet attempts to upload zero files if `uploadAllFiles` is triggered when there are no valid files to upload.

Version 0.10.0 of Droplet had the following check to prevent that:

```javascript
if ($ember.get(this, 'validFiles').length === 0) {
    // Determine if there are even files to upload.
    return false;
}
```

Is there a reason why this was removed? Can the check be restored?

### PR DESCRIPTION
**Pull request by simenheg**
Don't attempt to upload files if there aren't any files to upload.

Fixes #106.

### CODE REVIEW

**Comment by Wildhoney** [comment]
Ideally if `uploadFiles` returns a promise, then it should **always** return a promise. Many developers may be relying on the promise with `.then`.

Could we instead `reject` the promise immediately if there are zero files?

Another solution is to disable the button if there are no valid files, which is something you can add on your end.

**Comment by simenheg** [comment]
> Another solution is to disable the button if there are no valid files, which is something you can add on your end.

Yes, but not when using `uploadImmediately`.

> Could we instead reject the promise immediately if there are zero files?

Hm, when using `uploadImmediately`, `uploadFiles` is triggered with a `send` call internally. How can user code handle the resulting promise rejection?

**Comment by Wildhoney** [comment]
In the case of `uploadImmediately`, I think a simple check [at this point](https://github.com/Wildhoney/EmberDroplet/blob/master/components/Droplet.js#L639-L641) on `addedModels.length` would be sufficient.

Agreed?

**Comment by simenheg** [comment]
That won't work if the file is invalid.

How about checking if there are any valid files before calling `uploadFiles`?

**Comment by Wildhoney** [comment]
:+1: https://github.com/Wildhoney/EmberDroplet/blob/master/components/Droplet.js#L639-L641

Please try with `v3.0.0`.

**Comment by simenheg** [comment]
That seemed to work!

Thanks, @Wildhoney.

**Pull request closed without merging**
